GET http://localhost:4000/tareas

################################

POST http://localhost:4000/tareas
Content-Type: application/json

{   
    "id": 2,
    "name": "tarea2",
    "puntos": 10,
    "materia": "materia1",
    "fechaEntrega": "2022-03-28"
}

################################

PUT http://localhost:4000/tareas/6242304ef17b02b1754680e4
Content-Type: application/json

{   
    "id": 2
}

################################

DELETE http://localhost:4000/tareas/6243b37d9c3ad166ec18db99
Content-Type: application/json


